// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrocujmlmitkwmlrkkkl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZyb2N1am1sbWl0a3dtbHJra2tsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwMjgxMDAsImV4cCI6MjA5MDYwNDEwMH0.mO8KTJRSc1BDUZfDkLiATmSSUEtYlO27C-wZ91M88ps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});